config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check

  resources :articles, only: [:index, :show, :new, :create] do
    post 'bookmark', on: :member
    get 'image', on: :member, to: 'articles#image' # Custom route for image requests
    resources :comments, only: :create
    collection do
      get 'bookmarked'
    end
  end

  resources :events, only: [:index, :show, :new, :create] do
    member do
      post 'going'
    end
  end

  get 'my_events' => 'events#my_events', as: :my_events

  resources :badges, only: [:show]
  get 'my_badges', to: 'users#my_badges', as: 'my_badges'
  resources :users, only: [:show]
end

app/views/shared/_article-card.html.erb
<%# app/views/shared/_article-card.html.erb %>
<div class="row card-container">
  <% @articles.each do |article| %>
    <div class="card card-styling">
      <div id="title-card">
        <h5 class="card-title"><strong><%= article.title %></strong></h5>
      </div>
      <% article.images.each do |image| %>
        <%= cl_image_tag image.key, class: "img-fluid text-image", style: "height: 200px; width: 100%; object-fit: cover;" %>
      <% end %>
      <div class="card-body"></div>
      <ul class="list-group list-group-flush border-0">
        <li class="list-group-item border-0">Author: <%= article.user.first_name %></li>
        <div id="card-date-comment" class="d-flex justify-content-between align-items-center w-100">
          <li class="list-group-item border-0">
            <span class="badge badge-pill badge-info" style="background-color: lightblue; border-radius: 20px;">Article</span>
          </li>
          <li class="list-group-item border-0 d-flex align-items-center" style="text-decoration: none;">
            <%= link_to bookmark_article_path(article), method: :post, remote: true, class: 'btn btn-link p-0', data: { turbo_method: 'post' }, id: "bookmark-#{article.id}", style: "text-decoration: none; margin-right: 10px;" do %>
              <i class="fa-regular fa-bookmark"></i>
            <% end %>
            <%= link_to "#{article_path(article)}#comments", class: "btn btn-link p-0", style: "text-decoration: none;" do %>
              <i class="fa-solid fa-comment"></i>
            <% end %>
          </li>
        </div>
      </ul>
      <div class="card-body d-flex justify-content-center">
        <%= link_to 'Show More Details', article_path(article), class: 'btn btn-primary', id: "show-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_articles-partial.html.erb
<%# app/views/shared/_articles-partial.html.erb %>
<div class="row">
  <%= link_to article_path(article), style: "text-decoration: none;" do %>
    <div class="col-12 mb-3">
      <div class="card text-image">
        <div class="card-body">
          <h5 class="card-title card-title-link"><strong><%= article.title %></strong></h5>
          <h6 class="card-subtitle mb-2 text-muted">By: <%= "#{article.user.first_name} #{article.user.last_name}" %></h6>
          <% article.images.each do |image| %>
            <div class="mb-2">
              <%= cl_image_tag image.key, class: "img-fluid text-image", style: "height: 200px; width: 100%; object-fit: cover;" %>
            </div>
          <% end %>
          <% if bookmark %>
            <div id="card-date-comment" class="d-flex justify-content-between align-items-center">
              <span class="badge badge-pill badge-info" style="background-color: lightblue; border-radius: 20px;">Article</span>
              <div class="d-flex" style="text-decoration: none;">
                <%= link_to bookmark_article_path(article), method: :post, remote: true, class: 'btn btn-link p-0', data: { turbo_method: :post }, style: "text-decoration: none; margin-right: 10px;" do %>
                  <i class="fa-solid fa-bookmark"></i>
                <% end %>
                <%= link_to "#{article_path(article)}#comments", class: "btn btn-link p-0", style: "text-decoration: none;" do %>
                  <i class="fa-solid fa-comment"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_badge_alert.html.erb
<!-- app/views/shared/_badge_alert.html.erb -->
<div class="alert alert-success" role="alert">
  Congratulations! You have received the <strong><%= badge.name %></strong> badge. <%= badge.description %>
</div>

app/views/shared/_bash.html.erb
<% @user.badges.each do |badge| %>
  <div class="bash-card">
      <%= link_to badge_path(badge) do %>
        <%= image_tag asset_path(badge.image), alt: badge.name, class: "badge-image mr-3", if: badge.image.present? %>
      <% end %>
      <div>
        <%= link_to badge_path(badge), class: "badge-name-link" do %>
          <h5 class="card-title mb-0"><%= badge.name %></h5>
        <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_event-card.html.erb
<div class="row card-container">
  <% @events.each do |event| %>
    <div class="card card-styling">
      <div id="title-card">
        <h5 class="card-title"><%= event.title %></h5>
      </div>
      <% event.images.each do |image| %>
        <%= cl_image_tag image.key%>
      <% end %>
      <div class="card-body"></div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Author: <%= event.user.first_name %></li>
        <div id="card-date-comment">
          <li class="list-group-item">Published: <%= event.created_at.strftime("%B %d, %Y") %> </li>
        </div>
        <div id="card-date-comment" class="d-flex justify-content-between align-items-center w-100">
          <li class="list-group-item border-0">
            <span class="badge badge-pill badge-primary" style="background-color: #007bff; color: white; border-radius: 20px;">Event</span>
          </li>
          <li class="list-group-item border-0 d-flex align-items-center" style="text-decoration: none;">
            <span><%= rand(1..15) %> <i class="fa-solid fa-person"></i></span>
          </li>
        </div>
      </ul>
      <div class="card-body d-flex justify-content-center">
        <%= link_to 'Show More Details', event_path(event), class: 'btn btn-primary', id: "show-button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_floating-button.html.erb
<a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center">
  <i class="fa-solid fa-arrow-up"></i>
</a>

app/views/shared/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->
<footer class="text-center text-white" style="background-color: #FE6F61;">
  <!-- Copyright -->
  <div class="text-center p-3 text-color" style="background-color: rgb(239,246,255)">
    © 2024 Copyright, @Gerardo @Warren @Ribot</a>
</div>
<!-- Copyright -->
</footer>
<!-- End of .container -->

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar-menu.html.erb
<div class="offcanvas offcanvas-start navbar-menu" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <%= link_to "#", class: "navbar-brand mx-auto menu-image" do %>
      <%= image_tag "surviving-montreal-new.png", class: "logo-small" %>
    <% end %>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Browse Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Post an Article", new_article_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Discover Events", events_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Plan an Event", new_event_path, class: "nav-link" %>
      </li>
      <li class="nav-item" id="badge-link">
        <% if user_signed_in? %>
          <%= link_to 'My Badges', my_badges_path, class: "nav-link" %>
          <% if current_user.unseen_badges_count > 0 %>
            <span class="badge badge-pill badge-primary"><%= current_user.unseen_badges_count %></span>
          <% end %>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign out",destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
      <span class="navbar-toggler-icon"></span>
  </button>
    <%= link_to root_path, class: "navbar-brand mx-auto" do %>
      <%= image_tag "surviving-montreal-new.png", class: "logo-small" %>
    <% end %>
    <button class="btn btn-outline-secondary" type="button" id="navbar-search-icon">
      <i class="fas fa-search"></i>
    </button>
    <%= render "shared/navbar-menu" %>
  </div>
</nav>

app/views/shared/_notification.html.erb
<%= turbo_stream.append "notifications" do %>
  <div id="notification" class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

app/views/shared/_search.html.erb
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: @search_url, method: :get, class: "d-flex", id: "search-form" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword",
            id: "search-input"
        %>
      <div class="input-group-btn" id="submit-button">
        <button class="btn btn-default" type="submit" >
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>
      </div>
    <% end %>
  </div>
</div>