config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check

  resources :articles, only: [:index, :show, :new, :create] do
    post 'bookmark', on: :member
    get 'image', on: :member, to: 'articles#image' # Custom route for image requests
    resources :comments, only: :create
    collection do
      get 'bookmarked'
    end
  end

  resources :events, only: [:index, :show, :new, :create] do
    member do
      post 'going'
    end
  end

  get 'my_events' => 'events#my_events', as: :my_events

  resources :badges, only: [:show]
  get 'my_badges', to: 'users#my_badges', as: 'my_badges'
  resources :users, only: [:show]
end

app/models/event.rb
# app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :users

  validates :title, presence: true
  validates :description, presence: true
  validates :event_date, presence: true
  validates :number_of_people, presence: true
  validates :location, presence: true

  has_many_attached :images
end

app/controllers/events_controller.rb
# app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:going, :my_events]

  def index
    @events = Event.all
    if params[:query].present?
      query = "%#{params[:query]}%"
      @events = @events.joins(:user).where(
        "events.title ILIKE :query OR users.first_name ILIKE :query OR users.last_name ILIKE :query",
        query: query
      )
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user

    if @event.save
      message = "Event created successfully!"
      if current_user.events.count == 1 && !current_user.badges.exists?(name: 'First Event Create')
        current_user.award_badge('First Event Create')
        current_user.check_winter_survival_badge
        message += " You have earned a new badge!"
      elsif current_user.badges.where(name: ['First Article', 'Attend Your First Event', 'First Event Create']).count >= 3
        message = "Congratulations! You've also received the 'Survived Your First Winter' badge."
      end
      redirect_to events_path, notice: message
    else
      flash.now[:alert] = @event.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def going
    message = "Bookings successfully!"
    @event = Event.find(params[:id])
    unless current_user.events.include?(@event)
      current_user.events << @event
      if current_user.events.count == 1 && !current_user.badges.exists?(name: 'Attend Your First Event')
        current_user.award_badge('Attend Your First Event')
        current_user.check_winter_survival_badge
        message += " You have earned a new badge!"
      end
      if current_user.badges.where(name: ['First Article', 'Attend Your First Event', 'First Event Create']).count >= 3
        message = "Congratulations! You've also received the 'Survived Your First Winter' badge."
      end
    end
    redirect_to my_events_path, notice: message
  end

  def my_events
    @events = current_user.events
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :event_date, :number_of_people, images: [])
  end
end

app/views/events/index.html.erb
<%# app/views/events/index.html.erb  %>

<% content_for :title, "Surviving Montreal: Upcoming Events" %>
  <h1 class="title-styling">Events</h1>
<div class="container">
  <div class="row">
    <%= render "/shared/search" %>
    <% @events.each do |event| %>
      <div class="col-12 mb-3">
        <%= link_to event_path(event), class: "card-link" do %>
          <div class="card text-image">
            <div class="card-body">
            <span class="badge badge-pill badge-primary" style="background-color: #007bff; color: white; border-radius: 20px; margin-bottom:10px;">Event</span>
              <h5 class="card-title"><%= event.title %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= event.user.first_name %></h6>
               <% event.images.each do |image| %>
                <div class="mb-2">
                  <%= cl_image_tag image.key, class: "img-fluid text-image", style: "height: 200px; width: 100%; object-fit: cover;" %>

                </div>
              <% end %>
              <p class="card-text"><%= event.location %></p>
              <p class="card-text"><small class="text-muted"><%= event.event_date %></small></p>
              <p class="card-text"><%= event.number_of_people %> people attending</p>

            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/my_events.html.erb
  <% content_for :title, "Surviving Montreal: Events I'm Attending" %>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h2>Events I'm Attending</h2>
      </div>
    </div>
    <div class="row">
      <% @events.each do |event| %>
        <div class="col-12 mb-3">
          <div class="card text-image">
            <div class="card-body">
              <h5 class="card-title"><%= event.title %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= event.user.first_name %></h6>
              <p class="card-text"><%= event.description %></p>
              <div class="mb-3">
                <% event.images.each do |image| %>
                  <%= cl_image_tag image.key, class: "img-fluid text-image", style: "height: 200px; width: 100%; object-fit: cover;" %>
                <% end %>
              </div>
              <p><strong>Location:</strong> <%= event.location %></p>
              <p><strong>Date:</strong> <%= event.event_date %></p>
              <p><strong>Number of People:</strong> <%= event.number_of_people %> attending</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Plan An Event</h1>
      <% if flash.now[:alert] %>
        <div class="alert alert-danger">
          <%= flash.now[:alert] %>
        </div>
      <% end %>
      <%= form_with model: @event, local: true, class: "needs-validation", novalidate: true do |f| %>
        <div class="mb-3">
          <%= f.label :title, class: "form-label" %>
          <%= f.text_field :title, class: "form-control text-input", required: true %>
          <div class="invalid-feedback">
            Please provide a title.
          </div>
        </div>
        <div class="mb-3">
          <%= f.label :description, class: "form-label" %>
          <%= f.text_area :description, class: "form-control text-input", rows: 5, required: true %>
          <div class="invalid-feedback">
            Please provide a description.
          </div>
        </div>
        <div class="mb-3">
          <%= f.label :Upload_Image, class: "form-label" %>
          <%= f.file_field :images, class: "form-control text-input", multiple: true %>
          <div class="invalid-feedback">
            Please provide an image URL.
          </div>
        </div>
        <div class="mb-3">
          <%= f.label :event_date, class: "form-label" %>
          <%= f.date_field :event_date, class: "form-control text-input", required: true %>
          <div class="invalid-feedback">
            Please provide an event date.
          </div>
        </div>
        <div class="mb-3">
          <%= f.label :location, class: "form-label" %>
          <%= f.text_field :location, class: "form-control text-input", required: true %>
          <div class="invalid-feedback">
            Please provide a location.
          </div>
        </div>
        <div class="mb-3">
          <%= f.label :number_of_people, class: "form-label" %>
          <%= f.number_field :number_of_people, class: "form-control text-input", required: true %>
          <div class="invalid-feedback">
            Please provide the number of people.
          </div>
        </div>
        <div class="button-styling">
          <%= f.submit "Plan Event", class: 'btn btn-primary'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<%# app/views/events/show.html.erb %>
<% content_for :title, "Surviving Montreal: Event - " + @event.title %>
<div class="container">
  <div class="row">
    <div class="col-12 mb-3">
      <div class=" text-image">
        <div class="card-body">
          <h1><%= @event.title %></h1>
          <p class="text-muted">Organized by: <%= @event.user.first_name %></p>

          <div class="mb-3">
            <% @event.images.each do |image| %>
              <%= cl_image_tag image.key, class: "img-fluid text-image", style: "height: 300px; width: 100%; object-fit: cover;" %>
            <% end %>
          </div>
          <p class="card-paragraph"><%= @event.description %></p>
          <p><strong>Location:</strong> <%= @event.location %></p>
          <p><strong>Date:</strong> <%= @event.event_date %></p>
          <p><strong>Number of People:</strong> <%= @event.number_of_people %> attending</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="d-flex button-styling container">
  <%= button_to "Attending", going_event_path(@event), method: :post, class: "btn btn-primary mr-2", id: "attending" %>
  <%= link_to "Unavailable", events_path, class: "btn btn-danger", id: "unavailable"%>
</div>